project:
  render:
    - docs/manuscript.qmd
    - docs/appendix.qmd

format:
  apaquarto-typst:
    mask: false
  # apaquarto-docx: default

title: "The role of cognateness in native spoken word recognition"
shorttitle: "Cognateness and recognition of foreign words"
keywords:
  - spoken word recognition
  - phonology
  - cognateness
  - language processing
  - nonnative speech
  - lexical processing
floatsintext: true
numbered-lines: true
mask: false
suppress-title-page: true
word-count: true
knitr:
  opts_chunk:
    fig.path: img/

author-note:
  disclosures:
    data-sharing: |
      All materials, data, and code used in this study are hosted in the Open Science Framework [https://osf.io/9fjxm/?view_only=751d6ab27ffd4dd4856e4c07c4372991) and a GitHub repository [https://github.com/gongcastro/translation-elicitation.git](https://github.com/gongcastro/translation-elicitation.git), along with additional notes. For reproducibility, a Docker image of the RStudio session is available on DockerHub ([https://hub.docker.com/repository/docker/gongcastro/translation-elicitation/general](https://hub.docker.com/repository/docker/gongcastro/translation-elicitation/general)).
    financial-support: |
      This study was supported by the Spanish Ministry for Science and Innovation and State Research Agency (Project PGC2018-101831-B-I00 financed by Spanish Ministry of Science Innovation and Universities (MCIU), Spanish Research Agency (AEI) and the European Regional Development Fund (ERDF), and by the Economic and Social Research Council (ESRC) (ES/S010947/1, UK). GGC was supported by a FPI research contract (PRE2019-088165). NSG was supported by an ICREA Academia 2019 award from the Catalan Institution for Research and Advanced Studies (ICREA). 
    conflict-of-interest: |
      The authors declare no conflicts of interest with regard to the funding source of this study.
    gratitude: |
      We are grateful to Irina Lepadatu and Nicola Gillen, and to the Speech Acquisition and Perception research group for their helpful feedback. We thank Xavier Mayoral, Silvia Blanch, Pamela Miller, and Cristina Cuadrado for their technical support. We also thank all participants who took part in the experiments.


author:
  - name: Gonzalo Garcia-Castro
    corresponding: true
    orcid: 0000-0002-8553-4209
    email: gonzalo.garcia@sjd.es
    affiliations:
      - id: sjd
        name: NeuroDevelopment and Comparative Cognition
        department: Institut de Recerca Sant Joan de Déu
        city: Esplugues de Llobregat, 08950
      - id: cbc
        name: Universitat Pompeu Fabra
        department: Center for Brain and Cognition
        city: Barcelona, 08005
  - name: Serene Siow
    orcid: 0000-0001-6482-2191
    email: s.siow@nus.edu.sg
    affiliations: 
      - ref: uo
        id: uo
        name: University of Oxford
        department: Department of Experimental Psychology
        city: Oxford, OX2 6GG
  - name: Kim Plunkett
    orcid: 0000-0003-0216-7480
    email: kim.plunkett@psy.ox.ac.uk
    affiliations: 
      - ref: uo 
  - name: Nuria Sebastian-Galles
    orcid: 0000-0001-6938-2498
    email: nuria.sebastian@upf.edu
    affiliations: 
      - ref: cbc

bibliography: "references.bib"
link-citations: true
editor: source
lang: en
freeze: false
fig-dpi: 800
echo: false
warning: false
