---
title: "The role of cognateness during word recognition in a non-native language"
author: "Gonzalo Garcia-Castro, Serene Siow, Núria Sebastian-Galles, and Kim Plunkett"
date: "16/03/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Understanding spoken words in a non-native language is easier when their translations to the native language are phonologically similar. Phonological similarity plays a more important role in low-proficiency bilinguals, compared to high-proficiency bilinguals, and points to the latter as relying more strongly on word-concept associations (conceptual route) than on cross-language word-to-word links (lexical route). Disentangling bilinguals' reliance on the conceptual and the lexical route during translation is challenging, given that both sources of information are present to some extent in both high- and low-proficiency bilinguals. In this study, we tested English and Spanish native speakers in a translation elicitation task, in which they listened to words in an unfamiliar language (Spanish or Catalan for English natives, and Catalan for Spanish natives), and then had to translate them to their native language. Given their lack of previous knowledge on the unfamiliar language, phonological similarity between the presented words and their correct translations was the only cue available for participants to succeed in the task. This allowed us to explore the informativeness of the lexical route for word translation, in the absence of information from the conceptual route. Our results indicate that participants benefited from the phonological similarity between translation equivalents: the more similar the word they listened to and its translational equivalent, the higher the probability of a correct translation. This effect was larger in Spanish participants translating Catalan words than in English participants translating Catalan or Spanish. These results point to cross-language word-to-word links as providing rich information during word translation. 
