project:
  render:
    - manuscript.qmd
format:
  arxiv-pdf:
    keep-tex: true  
    linenumbers: true
    doublespacing: false
    runninghead: "Cognateness and recognition of foreign words"
    include-in-header: 
      text: |
        \usepackage{tipa}
        \usepackage{booktabs}
    authorcols: true
    knitr:
      opts_chunk:
        dev: "cairo_pdf"
    filters: 
      - "_extensions/andrewheiss/wordcount/citeproc.lua"
      - "_extensions/andrewheiss/wordcount/wordcount.lua"
  docx:
    reference-doc: _assets/template.docx
  typst:
    template-partials: 
      - _assets/typst-template.typ


title: "The role of cognateness in native spoken word recognition"
short-title: "Cognateness and recognition of foreign words"
author:
  - name: Gonzalo Garcia-Castro
    corresponding: true
    orcid: 0000-0002-8553-4209
    email: gonzalo.garciadecastro@upf.edu
    affiliations:
      - id: cbc
        name: Universitat Pompeu Fabra
        department: Center for Brain and Cognition
        city: Barcelona, 08005
  - name: Serene Siow
    orcid: 0000-0001-6482-2191
    email: siow.serene@gmail.com
    affiliations: 
      - ref: uo
        id: uo
        name: University of Oxford
        department: Department of Experimental Psychology
        city: Oxford, OX2 6GG
  - name: Kim Plunkett
    orcid: 0000-0003-0216-7480
    email: kim.plunkett@psy.ox.ac.uk
    affiliations: 
      - ref: uo 
  - name: Nuria Sebastian-Galles
    orcid: 0000-0001-6938-2498
    email: nuria.sebastian@upf.edu
    affiliations: 
      - ref: cbc
keywords:
  - cognate
  - spoken word recognition
  - phonology
  - bilingualism
  - non-native speech processing
  - lexical access
csl: "_assets/apa7.csl"
bibliography: "_assets/references.bib"
link-citations: true
editor: source
lang: en
freeze: true
fig-dpi: 1000
echo: false
warning: false

abstract: |
  While listening to speech in an unfamiliar language, words and phrases in the native language are activated, leading to common auditory illusions like Soramimi, a particular case of homophonic translation. Homophonic translation has received little attention as a psycholinguistic phenomenon. In this study, we explored the mechanisms underlying lexical activation and selection in homoponic translation. Across three studies, English and Spanish native adults completed a translation elicitation task, in which they listened to a series of Catalan or Spanish words (to which participants were unfamiliar), and then had to type their best-guess translation in their native language. Both English and Spanish natives were surprisingly good at translating unfamiliar words, efficiently exploiting the phonological similarity between the presented (unfamiliar) words and their correct translation. When the correct translation belonged to high-density phonological neighbours, participants' ability to benefit from phonological similarity decreased. Finally, Spanish natives exploited phonological similarity more efficiently: provided identical phonological similarity, Spanish natives were more likely to guess the correct translation of the unfamiliar word than English natives. Overall, we show that speech in an unfamiliar language triggers equivalent dynamics of lexical selection than native speech, providing a psycholinguistic account for homophonic translation.

thanks: |
  The authors declare no conflicts of interest with regard to the funding source of this study. This study was supported by the Spanish Ministry for Science and Innovation and State Research Agency (Project PGC2018-101831-B-I00 financed by Spanish Ministry of Science Innovation and Universities (MCIU), Spanish Research Agency (AEI) and the European Regional Development Fund (ERDF), and by the Economic and Social Research Council (ESRC) (ES/S010947/1, UK). GGC was supported by a FPI research contract (PRE2019-088165). SS was supported by XXXXXXXXXXXXX. KP was supported by XXXXXXXXXXXXXXXXX. NSG was supported by an ICREA Academia 2019 award from the Catalan Institution for Research and Advanced Studies (ICREA). We are grateful to Irina Lepadatu and Nicola Gillen, and to the Speech Acquisition and Perception research group for their helpful feedback. We thank Xavier Mayoral, Silvia Blanch, Pamela Miller, and Cristina Cuadrado for their technical support. We also thank all families and infants who participated in the experiments. This study was conducted according to guidelines laid down in the Declaration of Helsinki, and was approved by the Drug Research Ethical Committee (CEIm) of the IMIM Parc de Salut Mar, reference 2020/9080/I. The data and code necessary to reproduce the analyses presented here are publicly accessible, as are the materials necessary to attempt to replicate the findings. The analyses presented here were not preregistered. Data, code, and materials for this research are available at the following URLs: [https://osf.io/hy984/](https://osf.io/hy984/), [https://github.com/gongcastro/translation-elicitation](https://github.com/gongcastro/translation-elicitation).

