project:
  render:
    - manuscript.qmd
abstract: |
    Understanding spoken words in a non-native language is easier when the words are phonologically similar to their translations into the listener's native language are phonologically similar. Phonological similarity plays a more important role in the language performance of low-proficiency bilinguals, compared to that of high-proficiency bilinguals., and This suggests that low-proficiency bilinguals may points to the latter as relying more strongly on cross-language word-to-word links (lexical route), while high-proficiency bilinguals rely more on word-concept associations (conceptual route) than on cross-language word-to-word links (lexical route). Disentangling bilinguals' reliance on the conceptual and lexical and conceptual routes during translation is challenging, given that both sources of information are present during spoken word comprehensionto some extent in both high- and low-proficiency bilinguals. In this study, we tested English and Spanish native speakers in a translation elicitation task, in which they listened to words in an unfamiliar language (Spanish or Catalan for English natives, and Catalan for Spanish natives), and then had to translate them to their native language. Given their lack of previous knowledge ion the unfamiliar tested language, phonological similarity between the presented words and their correct translations was the only cue available for participants to succeed in the task. This allowed us to explore the informativeness of the lexical route for word translation, in the absence of information from the conceptual route. Our results indicate that participants benefited from the phonological similarity between translation equivalents: the more similar the word they listened to and its translational equivalent, the higher the probability of a correct translation. These results point to cross-language word-to-word links as providing rich information during word translation.
format:
  arxiv-pdf:
    keep-tex: true  
    linenumbers: true
    doublespacing: false
    runninghead: "Cognateness and non-native word recognition"
    include-in-header: 
      text: |
        \usepackage{tipa}
        \usepackage{booktabs}
    knitr:
      opts_chunk:
        dev: "cairo_pdf"
    filters: 
      - "_extensions/andrewheiss/wordcount/citeproc.lua"
      - "_extensions/andrewheiss/wordcount/wordcount.lua"

title: "The role of cognateness in non-native spoken word recognition"
short-title: "Cognate beginnings"
author:
  - name: Gonzalo Garcia-Castro
    corresponding: true
    orcid: 0000-0002-8553-4209
    email: gonzalo.garciadecastro@upf.edu
    affiliations:
      - id: cbc
        name: Universitat Pompeu Fabra
        department: Center for Brain and Cognition
        city: Barcelona, 08005
  - name: Serene Siow
    orcid: 0000-0001-6482-2191
    email: siow.serene@gmail.com
    affiliations: 
      - ref: uo
      - id: uo
        name: University of Oxford
        department: Department of Experimental Psychology
        city: Oxford, OX2 6GG
  - name: Kim Plunkett
    orcid: 0000-0003-0216-7480
    email: kim.plunkett@psy.ox.ac.uk
    affiliations: 
      - ref: uo 
  - name: Nuria Sebastian-Galles
    orcid: 0000-0001-6938-2498
    email: nuria.sebastian@upf.edu
    affiliations: 
      - ref: cbc
keywords:
  - cognate
  - spoken word recognition
  - phonology
  - bilingualism
  - non-native speech processing
  - lexical access
csl: "_assets/apa7.csl"
bibliography: "_assets/references.bib"
link-citations: true
editor: source
lang: en
freeze: true
fig-dpi: 1000
echo: false
warning: false

