---
---

```{r appendix-diagnostics, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

tar_load_globals()
tar_load(stimuli)
tar_load(participants)
tar_load(responses)
tar_load(model_fits)

suppressWarnings({
  bayesplot_theme_set(
    new = theme_custom() + 
      theme(
        axis.text.x = element_text(size = 8), 
        axis.text.y = element_text(size = 8),
        strip.text = element_text(size = 10),
        legend.key = element_rect(colour = NA, fill = "white")
      )
  )
})

color_scheme_set("brightblue")
pars <- c("b_Intercept", "b_frequency_zipf", "b_pthn", "b_lv", "b_pthn:lv")

```


# Appendix 1: Stan code

```{r appendix-code, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
model_fits$fit_3$model
```

# Appendix 2: MCMC diagnostics

## Pairs plot

```{r appendix-mcmc, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
posterior_cp <- as.array(model_fits$fit_3)
np_cp <- nuts_params(model_fits$fit_3)

plot_pairs <- mcmc_pairs(
  posterior_cp, pars = pars,
  off_diag_args = list(size = 0.75)
)

plot_pairs
```

## Trace plots

```{r appendix-trace, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
(mcmc_trace(model_fits$fit_3, pars) + legend_none()) /
  mcmc_rank_overlay(model_fits$fit_3, pars = pars) +
  plot_layout(guides = "collect") &
  theme(
    legend.position = "top"
  )
```

## Gelman-Rubin convergence criterion (R-hat)

```{r appendix-rhat, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
rhats <- rhat(model_fits$fit_3)
ratios <- neff_ratio(model_fits$fit_3)

mcmc_rhat_hist(rhats, binwidth = 0.00025, color = "white") + 
  mcmc_neff_hist(ratios, binwidth = 0.1) +
  plot_layout(guides = "keep", ncol = 1) &
  theme(
    legend.position = "right"
  )
```

# Appendix 3: by item accuracy

```{r appendix-accuracy, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, fig.cap="Proportion of correct translation by item. Words presented to participants in the English-Spanish or in the English-Catalan and Spanish-Catalan are listed in the Y-axis, ordered from higher to lower average translation accuracy, depicted in the X-axis. Dots and whiskers represent the average accuracy and 95% confidence interval of each word. Accuracy is plotted separately for each group."}

responses_item <- responses %>%
  group_by(trial_id, group, word) %>%
  summarise(
    correct_sum = sum(correct, na.rm = TRUE),
    correct_n = sum(!is.na(correct), na.rm = TRUE),
    .groups = "drop"
  ) %>% 
  left_join(select(stimuli, group, trial_id, word2, ipa1, ipa2)) %>% 
  mutate(
    word = paste0(word, " (", ipa1, ") / ", word2, " (", ipa2, ")"),
    correct_prop = prop_adj(correct_sum, correct_n),
    correct_se = prop_adj_se(correct_sum, correct_n),
    word_label = reorder_within(word, by = correct_prop, within = group)
  ) 


ggplot(responses_item, aes(reorder(word_label, correct_prop), correct_prop, ymin = correct_prop-correct_se, ymax = correct_prop+correct_se, colour = group)) +
  facet_wrap(~group, scales = "free_y") +
  geom_hline(yintercept = 0.5, colour = "black") +
  geom_errorbar(width = 0) +
  geom_point(size = 0.5) +
  labs(y = "Proportion of correct responses", x = "Word", colour = "Group") +
  coord_flip() +
  scale_color_manual(values = c("#1E88E5", "#ff2976", "#FFC20A")) +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent) +
  scale_x_discrete(labels = function(x) str_remove(x, "___ENG-CAT|___ENG-SPA|___SPA-CAT")) +
  theme(
    legend.position = "none",
    axis.text.y = element_text(size = 5, colour = "black"),
    axis.ticks = element_blank(),
    axis.text.x = element_text(size = 9, colour = "black"),
    panel.grid.major.x = element_line(colour = "grey", linetype = "dotted")
  )

```