---
title             : "A Phoneme-weighted Levenshtein Distance: A Measure of Cross-linguistic Phonological Similarity"
shorttitle        : "Translation Elicitation"

author: 
  - name          : "Serene Siow"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Anna Watts Building, Radcliffe Observatory Quarter, Woodstock Rd, Oxford, Oxfordshire OX2 6GG, UK"
    email         : "serene.siow@psy.ox.ac.edu"
  - name          : "Gonzalo García-Castro"
    affiliation   : "2"
  - name          : "Núria Sebastian-Galles"
    affiliation   : "2"
  - name          : "Kim Plunkett"
    affiliation   : "1"
affiliation:
  - id            : "1"
    institution   : "Department of Experimental Psychology, Oxford University"
  - id            : "2"
    institution   : "Center for Brain and Cognition, Universitat Pompeu Fabra"

authornote: |
  SS and GGC share first authorship.

abstract: |
  Many studies in bilingualism have explored how form similarity between translation equivalents (i.e. cognate- ness) impacts language processing. Cognates range from being identical to sharing only a few key features. Although there exists some objective measures of orthographic similarity between word-forms, there is still no representative equivalent for phonological similarity. In infant bilingual research, a measure that reflects perceptual similarity of spoken words as presented in infant-directed speech would be of great value. A widely used metric for word similarity is Levenshtein distance [@levenshtein1966binary]. This measure calculates word-form similarity by computing the smallest total number of substitutions, insertions and deletions needed to change one word to the other. However, a challenge when defining phonological similarity is that some phonemes (e.g. [k] and [g]) are perceptually more similar than others (e.g. [k] and [o]). The standard Lev- enshtein distance calculation treats each change equally. Thus it often overestimates phonological distance between words. We are developing an adaptation of Levenshtein distance for phonological representations, where edit operations are weighted according to the degree of phonemic feature changes involved, type of change (e.g. vowel or consonant insertion) and position in the word. To estimate the weights, we are collecting behavioural data in an auditory translation elicitation task. Monolingual adult participants with no exposure to the target language will be asked to guess and produce the translations of auditorily-presented words. The only way for participants to guess the correct translation is by mapping the presented unknown phonological form onto the phonology of its known translational equivalent. Cross-linguistic phonological similarity will be operationalised as the probability that participants correctly guess the corresponding trans- lation. The higher the probability, the higher the perceptual similarity. Our weighted similarity metric will provide a useful tool for identifying phonological similarity between words in infant-directed speech.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r prepare}
library(dplyr)
library(tidyr)
library(ggplot2)
library(here)
```

# Introduction

# Methods

## Algorithm

## Behavioural experiment

### Participants

### Stimuli

### Procedure

### Design

### Data analysis

We fit a generalised Bayesian hierarchical model, with accuracy as dependent variable and 

## Results

# Discussion

\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
