---
title: "Comparing jTRACE Output with Translation Elicitation Task"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(ggplot2)

```


```{r load jtrace output}
filedir <- "data/" 
# directory with save files (
  ## 1 file per input word, with 1 output word per column
  ## files should be named with input word orthography and language (e.g. "gato_spanish.xlsx")
  ## files should be xlsx (csv doesn't deal well with special characters)
  ## folder should not contain any other files
fnames <- dir(filedir) # extract list of file names in directory

trace_output <- data.frame() # create empty data frame

# for loop to extract highest activations for each input word
for (i in 1:length(fnames)){
  filename <- paste(filedir, fnames[i], sep = "") # get file name
  temp <- read_excel(filename) # read file
  
  temp <- apply(temp,2,max) # get highest value in each column
  temp <- as.data.frame(temp)
  temp <- cbind(newColName = rownames(temp), temp) # change index column (which has output items) into column 1 for easier organisation
  rownames(temp) <- 1:nrow(temp)
  names(temp)[1] <- "output" # (rename col) output item
  names(temp)[2] <- "activation" # (rename col) max activation value

  temp <- temp %>%
    filter(!output == "cycle") %>% # remove row corresponding to cycle number
    mutate(input = fnames[i]) %>% # specify input word
    arrange(desc(activation))
  
  trace_output <- bind_rows(trace_output, temp)
}

trace_output <- trace_output %>%
  mutate(input = str_remove(input, ".xlsx")) %>%
  separate(input, c("input", "language"), "_")


```


```{r match word}

# xlsx file with 1 column for TRACE transcriptions and 1 column for orthography (English words) 
df_transcription <- read_excel("trace_transcription.xlsx") %>%
  select(trace_eng, ort_eng) %>%
  unique()

# Match the jTRACE output transcriptions with their orthography
trace_output <- left_join(trace_output, df_transcription, by = c("output" = "trace_eng")) %>%
  rename(output_word = ort_eng)


```


```{r load translation task}

# Cleaned file with participant answers, 1 row per trial per participant
TranslationTask <- read.csv("translation_engdata_cleaned.csv") %>%
  mutate(test_language = tolower(test_language))

# count the number of participants who gave each answer in response to a given trial
df_answer <- TranslationTask %>%
  group_by(test_language, word, answer) %>%
  summarise(n_participant = n()) %>%
  group_by(test_language, word) %>%
  mutate(pct_participant = n_participant/sum(n_participant)*100, .groups = "drop") %>%
  filter(!n_participant == 1) # remove answers only given by 1 participant as idiosyncratic answers?

df_match <- left_join(df_answer, trace_output, by = c("word" = "input", "answer" = "output_word", "test_language" = "language"))

```


```{r plot, warning = FALSE}

ggplot(df_match, aes(x = activation, y = pct_participant)) +
  geom_smooth() +
  geom_point()


```


