---
title: "Additional analyses"
format: html
---

## Additional analyses

### Previous familiarity

```{r}
#| label: familiarity-frequency
#| fig-height: 10
#| fig-width: 10
familiarity_problematic <- here("data", "familiarity", "familiarity.xlsx") %>% read_xlsx() %>% 
    rename(
        word = presented,
        word_2 = translation,
        test_language = language,
        problem = note
    ) %>% 
    mutate(
        problem = ifelse(
            str_detect(problem, "check coding"), 
            "Check coding",
            str_to_sentence(problem)
        ),
        group = ifelse(test_language=="Catalan", "cat-ENG", "spa-ENG")
    ) %>% 
    select(word, group, problem)


familiarity <- stimuli %>% 
    filter(group != "cat-SPA") %>%
    mutate(
        stim = paste0(
            word_1, " /", ipa_flat_1, "/", " - ",
            word_2, " /", ipa_flat_2, "/", " - ",
            percent(lv, accuracy = 1)
        ),
        test_language = case_when(
            group=="cat-ENG" ~ "Catalan",
            group=="spa-ENG" ~ "Spanish",
            group=="cat-SPA" ~ "Catalan"
        ),
        word = replace_non_ascii(word_1)
    ) %>% 
    left_join(familiarity_problematic) %>% 
    select(group, word = word, stim, problem) %>% 
    left_join(filter(subtlex, test_language=="English")) %>% 
    replace_na(list(frequency_count = 1, frequency_zipf = 0.555, problem = "Normal")) %>% 
    left_join(select(word_accuracy, group, stim, prop,prop_se)) %>% 
    group_by(group) %>% 
    mutate(word_reorder = reorder_within(word, frequency_zipf, group)
    ) %>% 
    ungroup()

familiarity %>% 
    ggplot() +
    aes(x = frequency_zipf, y = word_reorder, fill = problem, colour = problem, label = word) +
    facet_wrap(~group, scales = "free_y") +
    geom_text(size = 3) +
    labs(
        x = "Frequency (Zipf) of presented word in English",
        y = "Word",
        colour = "Problem"
    ) +
    scale_colour_manual(values = my_colours, na.translate = FALSE) +
    scale_y_reordered() +
    theme(
        legend.position = "top",
        panel.border = element_rect(fill = NA, colour = "grey"),
        panel.grid.major.x = element_line(colour = "grey", linetype = "dotted"),
        legend.title = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank()
    )

ggsave(here("img", "problematic_frequency-distribution.png"), height = 10)

```

```{r}
#| label: previous-familiarity
#| fig-height: 3.5
#| fig-width: 8
familiarity %>% 
    filter(group != "cat-SPA") %>% 
    ggplot() +
    aes(x = frequency_zipf, y = prop, colour = problem, fill = problem, label = word) +
    facet_wrap(~group) +
    geom_text(size = 3) +
    # geom_point(
    #   shape = 1,
    #   size = 1,
    #   alpha = 0.5,
    #   stroke = 1
    # ) +
    geom_smooth(method = "lm", colour = "black", fill = "grey") +
    labs(
        x = "Frequency (Zipf) of presented word in English",
        y = "Accuracy",
        colour = "Group",
        fill = "Group"
    ) +
    scale_colour_manual(values = my_colours, na.translate = FALSE) +
    # scale_x_continuous(
    #   limits = c(2, 6)
    # ) +
    # scale_y_continuous(
    #   limits = c(0, 1),
    #   labels = percent
    # ) +
    theme(
        legend.position = "none"
    )

ggsave(here("img", "problematic_frequency-accuracy.png"), height = 4, width = 10)


```